import { CELL, type Grid } from "./pixel";

// The grids below are the source of truth and are edited by hand; the one-off generator that
// first drew them is not part of the repo.
// Room props as pixel grids at 2 px per cell, same legend as the figures (pixel.ts).
// Isometric 2:1 like the desk; light from the top left.

// Door in the back-left wall (the wall rises to the right): wood leaf, lit frame, metal handle. 20x60 cells.
export const DOOR: Grid = [
  "....................",
  "..................66",
  "................::66",
  "..............::WW66",
  "............::WWWw66",
  "..........::WWWwww66",
  "........::WWWwwwww66",
  "......::WWWwwwwwww66",
  "....::WWwwwwwwwwww66",
  "..::WWwwwwwwwwwWww66",
  "::WWwwwwwwwwwW6Www66",
  "::wwwwwwwwwW66WWww66",
  "::wwwwwwWW66WWWWww66",
  "::wwwwWWW6WWWWWWww66",
  "::wwWWW6WWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWW:Www66",
  "::wwW6WWWWWW::WWww66",
  "::wwW6WWWW::WWwwww66",
  "::wwW6WW::WWwwwwww66",
  "::wwW6::Wwwwwwwwww66",
  "::wwW:Wwwwwwwwwwww66",
  "::wwWwwwwwwwwwwWww66",
  "::wwwwwwwwwwwW6Www66",
  "::wwwwwwwwwW66WWww66",
  "::wwwwwwWW66WW~mww66",
  "::wwwwWWW6WWWWmmww66",
  "::wwWWW6WWWWWWW7ww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWWWWww66",
  "::wwW6WWWWWWWW:Www66",
  "::wwW6WWWWWW::WWww66",
  "::wwW6WWWW::WWwwww66",
  "::wwW6WW::WWwwwwww66",
  "::wwW6::Wwwwwwwwww77",
  "::wwW:Wwwwwwwwww77..",
  "::wwWwwwwwwwww77....",
  "::wwwwwwwwww77......",
  "::wwwwwwww77........",
  "::wwwwww77..........",
  "::wwww77............",
  "::ww77..............",
  "::77................",
  "77..................",
];

// Counter along the back-right wall: wood top, plastic cabinet doors, metal handles. 47x45 cells.
export const COUNTER: Grid = [
  "...............................................",
  "...............................................",
  "...............................................",
  "...............................................",
  "............::.................................",
  "...........:wwww...............................",
  "........:::wwwwwww.............................",
  ".......:wwwwwwwwwwww...........................",
  "....:::wwwwwwwwwwwwwww.........................",
  "...:wwwwwwwwwwwwwwwwwwww.......................",
  ".::wwwwwwwwwwwwwwwwwwwwwww.....................",
  ".Wg:wwwwwwwwwwwwwwwwwwwwwwww...................",
  ".gWWW::wwwwwwwwwwwwwwwwwwwwwww.................",
  ".ggggWg:wwwwwwwwwwwwwwwwwwwwwwww...............",
  ".gggggWWW::wwwwwwwwwwwwwwwwwwwwwww.............",
  ".gg==ggggWg:wwwwwwwwwwwwwwwwwwwwwwww...........",
  ".gg8g==gggWWW::wwwwwwwwwwwwwwwwwwwwwww.........",
  ".gg8ggg==ggggWg:wwwwwwwwwwwwwwwwwwwwwwww.......",
  ".gg8ggggg==gggWWW::wwwwwwwwwwwwwwwwwwwwwww.....",
  ".gg8ggggggg==ggggWg:wwwwwwwwwwwwwwwwwwwwwwww...",
  ".gg8ggggggggg==gggWWW::wwwwwwwwwwwwwwwwwwwwwww.",
  ".gg8ggggggggggg==ggggWg:wwwwwwwwwwwwwwwwwwww8W.",
  ".gg8gggggggggggg8x=gggWWW::wwwwwwwwwwwwwwwWWW8.",
  ".gg8gggggggggggg8x8==ggggWg:wwwwwwwwwwww8W8888.",
  ".gg8gggggggggggg8x8gg==gggWWW::wwwwwwwWWW88888.",
  ".gg8ggggggggggg~8x8gggg==ggggWg:wwww8W88888888.",
  ".gg8ggggggggggg~8x8gggggg==gggWWW:WWW888888888.",
  ".xggggggggggggg~8x8~ggggggg==ggggW888888888888.",
  ".gxxxggggggggggg8x8~ggggggggg==gg8888888888888.",
  "...ggxgggggggggg8x8~ggggggggggg=g8888888888888.",
  ".....gxxxggggggg8x8gggggggggggg8g8888888888888.",
  ".......ggxgggggg8x8gggggggggggg8g8888888888888.",
  ".........gxxxggg8x8gggggggggggg8g8888888888888.",
  "...........ggxgggx8gggggggggggg8g8888888888888.",
  ".............gxxxgggggggggggggg8g8888888888888.",
  "...............ggxggggggggggggg8g8888888888888.",
  ".................gxxxgggggggggg8g8888888888888.",
  "...................ggxggggggggg8g888888888888x.",
  ".....................gxxxgggggg8g888888888xxx8.",
  ".......................ggxggggg8g88888888x88...",
  ".........................gxxxgg8g88888xxx8.....",
  "...........................ggxggg8888x88.......",
  ".............................gxxx8xxx8.........",
  "...............................ggx88...........",
  ".................................8.............",
];

// Coffee machine: plastic body, metal tank, lit button, a cup under the spout. 20x26 cells.
export const COFFEE_MACHINE: Grid = [
  "..........~.........",
  "........~~~~~.......",
  "......~~~~~~~~~.....",
  "....==mm~~~~~~~~~...",
  "..====mmmm~~~~~77...",
  "======mmmmmm~7777...",
  "gg======mmmm77777==.",
  "gggg======mm777==88.",
  "gggggg======7==8888.",
  "ggggg~g!=====888888.",
  "ggggggggcg=88888888.",
  "gggggggggg888888888.",
  "ggx7gggggg888888888.",
  "ggx777gggg888888888.",
  "ggxxx777gg888888888.",
  "ggxxxxx7xg888888888.",
  "ggxx~mxxxg888888888.",
  "ggxxmMxxxg888888888.",
  "ggxxMMxxxg888888888.",
  "gg7gxxxxxg888888888.",
  "ggg777xxxg888888888.",
  "..gggg7gxg888888888.",
  "....ggg77g8888888...",
  "......gggg88888.....",
  "........gg888.......",
  "..........8.........",
];

// Counter with the machine and paper cups on top, as placed in the room. 47x61 cells.
export const COFFEE_STATION: Grid = [
  "...............................................",
  "...............................................",
  "...............................................",
  "...............................................",
  "...............................................",
  "...............................................",
  "...............................................",
  "...............................................",
  "...............................................",
  "...............................................",
  ".................................~.............",
  "...............................~~~~~...........",
  ".............................~~~~~~~~~.........",
  "...........................==mm~~~~~~~~~.......",
  ".........................====mmmm~~~~~77.......",
  ".......................======mmmmmm~7777.......",
  ".......................gg======mmmm77777==.....",
  ".......................gggg======mm777==88.....",
  ".......................gggggg======7==8888.....",
  ".......................ggggg~g!=====888888.....",
  "............::.........ggggggggcg=88888888.....",
  "...........:wwww.......gggggggggg888888888.....",
  "........:::wwwwwww.....ggx7gggggg888888888.....",
  ".......:wwwwwwwwwwww...ggx777gggg888888888.....",
  "....:::wwwwwwwwwwwwwww.ggxxx777gg888888888.....",
  "...:wwwwwwwwwwwwwwwwwwwggxxxxx7xg888888888.....",
  ".::wwwwwwwwwfffwwwwwwwwggxx~mxxxg888888888.....",
  ".Wg:wwwwwwwwfFfwwwwwwwwggxxmMxxxg888888888.....",
  ".gWWW::wwwwwfFfwwwwwwwwggxxMMxxxg888888888.....",
  ".ggggWg:wwwwFFFwfffwwwwgg7gxxxxxg888888888.....",
  ".gggggWWW::wwwwwfFfwwwwggg777xxxg888888888.....",
  ".gg==ggggWg:wwwwFFFwwwwwwgggg7gxg888888888.....",
  ".gg8g==gggWWW::wwwwwwwwwwwwggg77g8888888.......",
  ".gg8ggg==ggggWg:wwwwwwwwwwwwwgggg88888ww.......",
  ".gg8ggggg==gggWWW::wwwwwwwwwwwwgg888wwwwww.....",
  ".gg8ggggggg==ggggWg:wwwwwwwwwwwww8wwwwwwwwww...",
  ".gg8ggggggggg==gggWWW::wwwwwwwwwwwwwwwwwwwwwww.",
  ".gg8ggggggggggg==ggggWg:wwwwwwwwwwwwwwwwwwww8W.",
  ".gg8gggggggggggg8x=gggWWW::wwwwwwwwwwwwwwwWWW8.",
  ".gg8gggggggggggg8x8==ggggWg:wwwwwwwwwwww8W8888.",
  ".gg8gggggggggggg8x8gg==gggWWW::wwwwwwwWWW88888.",
  ".gg8ggggggggggg~8x8gggg==ggggWg:wwww8W88888888.",
  ".gg8ggggggggggg~8x8gggggg==gggWWW:WWW888888888.",
  ".xggggggggggggg~8x8~ggggggg==ggggW888888888888.",
  ".gxxxggggggggggg8x8~ggggggggg==gg8888888888888.",
  "...ggxgggggggggg8x8~ggggggggggg=g8888888888888.",
  ".....gxxxggggggg8x8gggggggggggg8g8888888888888.",
  ".......ggxgggggg8x8gggggggggggg8g8888888888888.",
  ".........gxxxggg8x8gggggggggggg8g8888888888888.",
  "...........ggxgggx8gggggggggggg8g8888888888888.",
  ".............gxxxgggggggggggggg8g8888888888888.",
  "...............ggxggggggggggggg8g8888888888888.",
  ".................gxxxgggggggggg8g8888888888888.",
  "...................ggxggggggggg8g888888888888x.",
  ".....................gxxxgggggg8g888888888xxx8.",
  ".......................ggxggggg8g88888888x88...",
  ".........................gxxxgg8g88888xxx8.....",
  "...........................ggxggg8888x88.......",
  ".............................gxxx8xxx8.........",
  "...............................ggx88...........",
  ".................................8.............",
];

// Floor plant in a plastic pot, tall leaves. 16x22 cells.
export const PLANT_TALL: Grid = [
  "....%...........",
  "....%e......e...",
  ".....ee....eE...",
  "..e...eE..eE....",
  "..ee..eE.eE.....",
  "...ee.eEeE....e.",
  ".%..eeeEeE...eE.",
  ".%e..eeEE...eE..",
  "..ee.%eEe..eE...",
  "...eeeeE9eeE....",
  "....%ee9eEE.....",
  ".....e9e9E......",
  "......999.......",
  "...=ggggggggG...",
  "..=g66666666g8..",
  "..=gggggggggG8..",
  "...=gggggggG8...",
  "...=gggggggG8...",
  "...=gggggggG8...",
  "....=ggggggG....",
  "....=ggggggG....",
  ".....888888.....",
];

// Floor plant in a plastic pot, round bush. 18x17 cells.
export const PLANT_BUSH: Grid = [
  "......%%ee........",
  "....%%eeeeEe......",
  "...%eeeeeeeeEE....",
  "..%eeEeeeeEeeeE...",
  "..eeeeeEeeeeeEE9..",
  ".%eeEeeeeeEeeeE9..",
  ".eeeeeeEeeeeEEE9..",
  ".eeEeeeeeeEeeE99..",
  "..eeeeEeeeEEE99...",
  "..9eEeeeEEE9999...",
  "...99EEE99999.....",
  "....=gggggggG.....",
  "...=g6666666g8....",
  "...=ggggggggG8....",
  "....=gggggggG.....",
  "....=gggggggG.....",
  ".....8888888......",
];

// The sheet a subagent carries and hands over. 7x10 cells.
export const PAPER: Grid = [
  "fffff..",
  "fFFFfff",
  "fffffff",
  "fFFFFFf",
  "fffffff",
  "fFFFFff",
  "fffffff",
  "fFFFfff",
  "fffffff",
  ".FFFFFF",
];

// Wall clock, face and rim only; the second hand is a CSS element over the centre. 11x11 cells.
export const CLOCK: Grid = [
  "...lllll...",
  "..lwwwwwl..",
  ".lwfffffwl.",
  "lwfffFfffwl",
  "lwfffffffwl",
  "lwfffllffwl",
  "lwfffffffwl",
  "lwfffffffwl",
  ".lwfffffwl.",
  "..lwwwwwl..",
  "...lllll...",
];

// Steam wisp over the coffee machine, light plastic, drifts up under CSS. 8x10 cells.
export const STEAM: Grid = [
  "..=.....",
  ".==.....",
  ".=......",
  "..==....",
  "...=....",
  "..==....",
  ".==.....",
  ".=......",
  "..=.....",
  "........",
];

export const PROPS = {
  DOOR,
  COUNTER,
  COFFEE_MACHINE,
  COFFEE_STATION,
  PLANT_TALL,
  PLANT_BUSH,
  PAPER,
  CLOCK,
  STEAM,
} as const;
export type PropName = keyof typeof PROPS;

// Drawn size in px; PixelProp in CharacterRig.tsx renders the grid.
export function propSize(name: PropName) {
  return { width: PROPS[name][0].length * CELL, height: PROPS[name].length * CELL };
}
