import type { Grid } from "./pixel";

// The grids below are the source of truth and are edited by hand; the one-off generator that
// first drew them is not part of the repo.
// Figure frames: 32x48 cells at 2 px per cell (64x96 box, foot origin at the bottom center).
// Bodies have a bare head; hair and headphones are separate 20x16 layers drawn at the
// frame's head anchor. Walking and standing frames face down-right, the seated frames face up-right (seen
// from behind); the other two facings are mirrors. Legend in pixel.ts.

export const SEATED_TYPING: Grid = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............kkkkk.............",
  "............kkkkkkkkk...........",
  "...........kkkkkkkkkkk..........",
  "...........kkkkkkkkkkk..........",
  "...........kkkkkkkkkkK..........",
  "...........kkkkkkkkkkK..........",
  "...........kkkkkkkkkKk..........",
  "...........KkkkkkkkkKk..........",
  "...........KkkkkkkkkkK..........",
  "............KkkkkkkkK...........",
  ".............KkkkkkK............",
  "..............KKKKK.....kkk..kk.",
  "............++KKKKKs....KK..1kkk",
  "........sss+sssssssssssS...s1KKk",
  "........+sS+ssssssssSssSssss1s..",
  "........+sS+ssssSsssSsssssss1S..",
  "........+sS+ssssSsssSssssssSSS..",
  "........+sSzzzzzSzzzSssssSSS....",
  "........+sSzggggggggSssSSS......",
  "........SSSg========gS.S........",
  "..........sg=gggggggGS..........",
  "..........sg=ggggggg8S..........",
  "..........sg=ggggggg8S...pppp...",
  "..........sg=ggggggg8Spppppp4...",
  "...........g=ggggggppppppppp4...",
  "...........g=ggggggpppppPpPp4...",
  "...........ggggggggpppPppPPP4...",
  "..........44GGGGGGGpPpppppPP4...",
  "..........44448888.ppp...pPP4...",
  "..........====ggggg8888..pPP4...",
  ".........=gggggggggggGGO555P4...",
  ".........5888888888888855l5555..",
  ".........5l55O.88......5555555O.",
  ".........lllll.88......llllllll.",
  "...........88888888888..........",
  "..........88..888...88..........",
  ".........gg...ggg....gg.........",
];

export const SEATED_RAISED: Grid = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  ".........................k.k.k..",
  ".........................k.k.k..",
  ".........................kkkkk..",
  ".........................kkkkkk.",
  "..........................kkkK..",
  "..............kkkkk........KK...",
  "............kkkkkkkkk.....111...",
  "...........kkkkkkkkkkk....+sS...",
  "...........kkkkkkkkkkk....+sS...",
  "...........kkkkkkkkkkK....+sS...",
  "...........kkkkkkkkkkK....+sS...",
  "...........kkkkkkkkkKk....+sS...",
  "...........KkkkkkkkkKk....+sS...",
  "...........KkkkkkkkkkK....+sS...",
  "............KkkkkkkkK.....+sS...",
  ".............KkkkkkK......+sS...",
  "..............KKKKK.....kkksS...",
  "............++KKKKKs....KKsss...",
  "........sss+ssssssssssssssss....",
  "........+sS+ssssssssSssssss.....",
  "........+sS+ssssSsssSsssss......",
  "........+sS+ssssSsssSssss.......",
  "........+sSzzzzzSzzzzZ..........",
  "........+sSzggggggggzZ..........",
  "........SSSg========gS..........",
  "..........sg=gggggggGS..........",
  "..........sg=ggggggg8S..........",
  "..........sg=ggggggg8S...pppp...",
  "..........sg=ggggggg8Spppppp4...",
  "...........g=ggggggppppppppp4...",
  "...........g=ggggggpppppPpPp4...",
  "...........ggggggggpppPppPPP4...",
  "..........44GGGGGGGpPpppppPP4...",
  "..........44448888.ppp...pPP4...",
  "..........====ggggg8888..pPP4...",
  ".........=gggggggggggGGO555P4...",
  ".........5888888888888855l5555..",
  ".........5l55O.88......5555555O.",
  ".........lllll.88......llllllll.",
  "...........88888888888..........",
  "..........88..888...88..........",
  ".........gg...ggg....gg.........",
];

export const SEATED_IDLE: Grid = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............kkkkk.............",
  "............kkkkkkkkk...........",
  "...........kkkkkkkkkkk..........",
  "...........kkkkkkkkkkk..........",
  "...........kkkkkkkkkkK..........",
  "...........kkkkkkkkkkK..........",
  "...........kkkkkkkkkKk..........",
  "...........KkkkkkkkkKk..........",
  "...........KkkkkkkkkkK..........",
  "............KkkkkkkkK...........",
  ".............KkkkkkK............",
  "..............KKKKK.............",
  "............++KKKKKs............",
  "........sss+sssssssssssS........",
  "........+sS+ssssssssSssS........",
  "........+sS+ssssSsssSssS........",
  "........+sS+ssssSsssSssS........",
  "........+sSzzzzzSzzzSssS........",
  "........+sSzggggggggSssS........",
  "........SSSg========gssS........",
  "..........sg=gggggggGsssS.......",
  "..........sg=ggggggg8SssSkkk....",
  "..........sg=ggggggg8SSSSKKkp...",
  "..........sg=ggggggg8Spppp2p4...",
  "...........g=ggggggppppppppp4...",
  "...........g=ggggggpppppPpPp4...",
  "...........ggggggggpppPppPPP4...",
  "..........44GGGGGGGpPpppppPP4...",
  "..........44448888.ppp...pPP4...",
  "..........====ggggg8888..pPP4...",
  ".........=gggggggggggGGO555P4...",
  ".........5888888888888855l5555..",
  ".........5l55O.88......5555555O.",
  ".........lllll.88......llllllll.",
  "...........88888888888..........",
  "..........88..888...88..........",
  ".........gg...ggg....gg.........",
];

export const WALK_A: Grid = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............;;kkk.............",
  "............;;kkkkkkk...........",
  "...........;kkkkkkkkkk..........",
  "...........kkkkkkkkkkk..........",
  "...........kkkkkkkkkkK..........",
  "...........kkkkk3kkk3K..........",
  "...........kkkkkxkkkxK..........",
  "...........KkkkkxkkkxK..........",
  "...........KKkkkkkkkkk..........",
  "...........KKkkkkkkkkK..........",
  "............Kkkkkkkkk...........",
  ".............Kkk2kk2K...........",
  "..............KKK22K............",
  "........++s.++SKKKKS............",
  "........sss+sssSSSSssSSS1.......",
  "........+sS+sssssssss1SS1.......",
  ".......+sSs+ssssssssS1SS1.......",
  ".......+sSs+ssssssssS1SS1.......",
  "......+sS.zzzzzzzzzzZ1SS1S......",
  "......+sS.zzzzzzzzzzZ1.SSSS.....",
  "......+sS.s+ssssssssS1..SSS.....",
  ".....+sS..s+ssssssssS1..SSfffff.",
  ".....+sS..s+sSsssssSS1...SfFFFFf",
  ".....SSS..ssssSsssSsS1...KKkffff",
  ".....kkk...SSSSSSSSSS....K2kFFff",
  ".....kkK...PPPPPPPPPP.....2fffFf",
  "......K....pppppppppp......FFFF.",
  "...........ppppPPPPP4...........",
  "..........ppppP.PPPP4...........",
  "..........ppPpP..PP4P4..........",
  ".........ppPpP...PP4P4..........",
  ".........ppPpP...PP4P4..........",
  "........O55pP....PP4P4..........",
  ".......55ll55.....PP4P4.........",
  "......5555555O...O555P4.........",
  "......lllllll....55ll555........",
  ".................5555555O.......",
  ".................llllllll.......",
  "................................",
  "................................",
  "................................",
  "................................",
];

export const WALK_B: Grid = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............;;kkk.............",
  "............;;kkkkkkk...........",
  "...........;kkkkkkkkkk..........",
  "...........kkkkkkkkkkk..........",
  "...........kkkkkkkkkkK..........",
  "...........kkkkk3kkk3K..........",
  "...........kkkkkxkkkxK..........",
  "...........KkkkkxkkkxK..........",
  "...........KKkkkkkkkkk..........",
  "...........KKkkkkkkkkK..........",
  "............Kkkkkkkkk...........",
  ".............Kkk2kk2K...........",
  "..............KKK22K............",
  "........++s.++SKKKKS............",
  "........sss+sssSSSSssSSS1.......",
  "........+sS+sssssssss1SS1.......",
  "........+sS+ssssssssS1SS1.......",
  "........+sS+ssssssssS1SS1.......",
  "........+sSzzzzzzzzzZ1SS1S......",
  "........+sSzzzzzzzzzZ1.SSSS.....",
  "........+sS+ssssssssS1..SSS.....",
  "........+sS+ssssssssS1..SSfffff.",
  "........+sS+sSsssssSS1...SfFFFFf",
  "........SSSsssSsssSsS1...KKkffff",
  "........kkkSSSSSSSSSS....K2kFFff",
  "........kkKPPPPPPPPPP.....2fffFf",
  ".........K.pppppppppp......FFFF.",
  "...........ppppPPPPP4...........",
  "...........ppppPPPP4............",
  "............ppPpPP4.............",
  "............ppPpP...............",
  "...........OppPpP...............",
  "..........55lppPpP..............",
  ".........5555ppPpP..............",
  ".........lllllppPpP.............",
  ".............O555pP.............",
  ".............55ll555............",
  ".............5555555O...........",
  ".............llllllll...........",
  "................................",
  "................................",
  "................................",
];

export const STANDING: Grid = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............;;kkk.............",
  "............;;kkkkkkk...........",
  "...........;kkkkkkkkkk..........",
  "...........kkkkkkkkkkk..........",
  "...........kkkkkkkkkkK..........",
  "...........kkkkk3kkk3K..........",
  "...........kkkkkxkkkxK..........",
  "...........KkkkkxkkkxK..........",
  "...........KKkkkkkkkkk..........",
  "...........KKkkkkkkkkK..........",
  "............Kkkkkkkkk...........",
  ".............Kkk2kk2K...........",
  "..............KKK22K............",
  "........++s.++SKKKKS............",
  "........sss+sssSSSSssSS.........",
  "........+sS+sssssssss11S1.......",
  "........+sS+ssssssssS11S1.......",
  "........+sS+ssssssssS11S1.......",
  "........+sSzzzzzzzzzZZ1S1.......",
  ".......+sSzzzzzzzzzzZZ1S1.......",
  ".......+sSs+ssssssssS11S1.......",
  ".......+sSs+ssssssssS11S1.......",
  ".......+sSs+sSsssssSS11S1.......",
  ".......SSSssssSsssSsS1111.......",
  ".......kkk.SSSSSSSSSS.KKK.......",
  ".......kkK.PPPPPPPPPP.KK2.......",
  "........K..pppp44pppp..2........",
  "...........ppppPPPPP4...........",
  "...........ppppPPPPP4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpO555P4...........",
  "..........O555p55ll555..........",
  "..........55ll55555555O.........",
  "..........5555555Olllll.........",
  "..........llllllll..............",
  "................................",
  "................................",
  "................................",
];

export const STANDING_MUG: Grid = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............;;kkk.............",
  "............;;kkkkkkk...........",
  "...........;kkkkkkkkkk..........",
  "...........kkkkkkkkkkk..........",
  "...........kkkkkkkkkkK..........",
  "...........kkkkk3kkk3K..........",
  "...........kkkkkxkkkxK..........",
  "...........KkkkkxkkkxK..........",
  "...........KKkkkkkkkkk..........",
  "...........KKkkkkkkkkK..........",
  "............Kkkkkkkkk...........",
  ".............Kkk2kk2K...........",
  "..............KKK22K............",
  "........++s.++SKKKKS............",
  "........sss+sssSSSSssSSS........",
  "........+sS+sssssssss1S1........",
  "........+sS+ssssssssS1S1..~mmm..",
  "........+sS+ssssssssS1S1.~6666m.",
  "........+sSzzzzzzzzzZ1S1kk~mmmM.",
  ".......+sSzzzzzzzzzzZ1SSKk~mmmM.",
  ".......+sSs+ssssssssS1SSK2~mmmM.",
  ".......+sSs+ssssssssS1.SS.~mmM..",
  ".......+sSs+sSsssssSS111...MM...",
  ".......SSSssssSsssSsS1..........",
  ".......kkk.SSSSSSSSSS...........",
  ".......kkK.PPPPPPPPPP...........",
  "........K..pppp44pppp...........",
  "...........ppppPPPPP4...........",
  "...........ppppPPPPP4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpPPP4P4...........",
  "...........ppPpO555P4...........",
  "..........O555p55ll555..........",
  "..........55ll55555555O.........",
  "..........5555555Olllll.........",
  "..........llllllll..............",
  "................................",
  "................................",
  "................................",
];

export const FRAMES = {
  SEATED_TYPING,
  SEATED_RAISED,
  SEATED_IDLE,
  WALK_A,
  WALK_B,
  STANDING,
  STANDING_MUG,
} as const;
export type FrameName = keyof typeof FRAMES;
export type View = "front" | "back";

export const FRAME_VIEW: Record<FrameName, View> = {
  SEATED_TYPING: "back",
  SEATED_RAISED: "back",
  SEATED_IDLE: "back",
  WALK_A: "front",
  WALK_B: "front",
  STANDING: "front",
  STANDING_MUG: "front",
};

// Top-left cell of the hair and headphone layers in each frame.
export const HEAD_ANCHOR: Record<FrameName, readonly [number, number]> = {
  SEATED_TYPING: [6, 5],
  SEATED_RAISED: [6, 5],
  SEATED_IDLE: [6, 5],
  WALK_A: [6, 0],
  WALK_B: [6, 0],
  STANDING: [6, 0],
  STANDING_MUG: [6, 0],
};

// Hair layers over the bare head; a seed picks one. Colors follow --hair.
export const HAIRSTYLES = [
  {
    name: "spiky",
    front: [
      ".........h..h.......",
      "......h..hh.hh..h...",
      "......hh^hhhhhhhh...",
      "...hh^^^hhhhhhhhhh..",
      "....h^^hhhhhhhhhhhh.",
      "...hh^hhhhhhhhhhhhH.",
      "..hhhhhhhhhhhhhhhHH.",
      "...hhhhhhhhhhhhhhHHh",
      "...hhhhhhhhhhhhhhHH.",
      "...hhhhhhhhHhhhHhH..",
      "...hhhhhhH.H..H..H..",
      "....hhhH............",
      "....hhhH............",
      ".....HH.............",
      "....................",
      "....................",
    ],
    back: [
      "........h..h........",
      ".....h..hh.hh..h....",
      ".....hh^hhhhhhhh....",
      "...hh^^^hhhhhhhhhh..",
      "...hh^^hhhhhHhhhhhh.",
      "..hhh^hhhhhHhhhhhhH.",
      "..hh^hhhHhhhhhhhhHH.",
      "...hhhhhHhhhhHhhhHHh",
      "...hhhhhhhhhhHhhhhH.",
      "..hhhhhHhhhhhhhhhhHH",
      "...hhhhHhhhhHhhhhhH.",
      "...hhhhhhhhhhHhhhHH.",
      "....hhHhhhhhhhhhhH..",
      "....hhhhhHhhhhhhHH..",
      ".....hHhhHhhHhhH....",
      "......H..H..H..H....",
    ],
  },
  {
    name: "crop",
    front: [
      "....................",
      "....................",
      "....................",
      "........hhhhh.......",
      "......h^^hhhhhh.....",
      ".....h^^hhhhhhhh....",
      "....hh^hhhhhhhhhh...",
      "....hhhhhhhhhhhhHH..",
      "....hhhhhhhhhhhhHH..",
      "....hhhhhhHHHHHHH...",
      "....hhhhH...........",
      "....hhhH............",
      ".....hH.............",
      "....................",
      "....................",
      "....................",
    ],
    back: [
      "....................",
      "....................",
      "....................",
      "........hhhhh.......",
      "......h^^hhhhhh.....",
      ".....h^^hhhhhhhh....",
      "....hh^hhhhhhhhhh...",
      "....h^hhhhhhhhhhHH..",
      "....hhhhhhhhhhhhHH..",
      "....hhhhhhhhhhhhhH..",
      "....hhhhhhhhhhhhhH..",
      "....hhhhhhhhhhhhH...",
      "....HhhhhhhhhhhhH...",
      ".....HHhhhhhhhHH....",
      "......HHHHHHHH......",
      "....................",
    ],
  },
  {
    name: "bun",
    front: [
      "...hhhh.............",
      "..h^^hhH............",
      "..h^hhhH............",
      "...hHHHhhhhh........",
      "......h^^hhhhhh.....",
      ".....h^^hhhhhhhh....",
      "....hh^hhhhhhhhhh...",
      "....hhhhhhhhhhhhHH..",
      "....hhhhhhhhhhhhhH..",
      "....hhhhhhhhHhhhhH..",
      "....hhhhhhH....hhH..",
      "....hhhhH.......hH..",
      "....hhhH........H...",
      ".....hH.............",
      "....................",
      "....................",
    ],
    back: [
      "........hhhh........",
      ".......h^^hhH.......",
      ".......h^hhhH.......",
      "......hHHHHHHh......",
      "......h^^hhhhhh.....",
      ".....h^^hhhhhhhh....",
      "....hh^hhhhhhhhhh...",
      "....h^hhhhhhhhhhHH..",
      "....hhhhhhHhhhhhHH..",
      "....hhhhhhHhhhhhhH..",
      "....hhhhhhHhhhhhhH..",
      "....hhhhhhHhhhhhH...",
      "....HhhhhhHhhhhhH...",
      ".....HHhhhHhhhHH....",
      "......HHHHHHHH......",
      "....................",
    ],
  },
  {
    name: "afro",
    front: [
      "......h^hh.hhh......",
      "....hh^^hhhhhhhh....",
      "...h^^^hhhhHhhhhh...",
      "..hh^^hhhHhhhhHhhh..",
      "..h^hhHhhhhhhhhhhhH.",
      ".hhhhhhhhhHhhhHhhhH.",
      ".hhhhHhhhhhhhhhhhHHH",
      ".hhhhhhhhhhhHhhhhHH.",
      "..hhhHhhhhhhhhhhhHHH",
      "..hhhhhhhHhhHhHhHHH.",
      "..hhhhhHH.H.H.H.HH..",
      "..hhhhhH........HH..",
      "...hhhhH............",
      "...hHhH.............",
      "....HH..............",
      "....................",
    ],
    back: [
      "......h^hh.hhh......",
      "....hh^^hhhhhhhh....",
      "...h^^^hhhhHhhhhh...",
      "..hh^^hhhHhhhhHhhh..",
      "..h^hhHhhhhhhhhhhhH.",
      ".hhhhhhhhhHhhhHhhhH.",
      ".hhhhHhhhhhhhhhhhHHH",
      ".hhhhhhhhhhhHhhhhHH.",
      ".hhhhHhhhhhhhhhhhHHH",
      "..hhhhhhhHhhHhhhHHH.",
      ".hhhhhhHhhhhhhHhhHHH",
      "..hhHhhhhhhHhhhhhHH.",
      "..hhhhhhhHhhhhHhHHH.",
      "...hhHhhhhhhhhhHHH..",
      "....HhhHhhHhhHhHH...",
      "......HH.HH.HH......",
    ],
  },
  {
    name: "side-part",
    front: [
      "....................",
      "....................",
      "........hhhhhh......",
      "......hhh^^^^hhh....",
      ".....hh^^hhhhhhhh...",
      "....hhhH^^^hhhhhhH..",
      "....hhhhHhh^^hhhhHH.",
      "....hhhhhhhhhhhhhhH.",
      "....hhhhhhhhhhhhhhHH",
      "....hhhhhHhhhhhhhHH.",
      "....hhhhh.HHhhhHH...",
      "....hhhhH......H....",
      "....hhhH............",
      ".....hH.............",
      "....................",
      "....................",
    ],
    back: [
      "....................",
      "....................",
      "........hhhhhh......",
      "......hhh^^^^hhh....",
      ".....hh^^hhhhhhhh...",
      "....hhhH^^^hhhhhhH..",
      "....hhhhHhh^^hhhhHH.",
      "....hhhhhhhhhhhhhhH.",
      "....hhhhhhhhhhhhhhHH",
      "....hhhhhhHhhhhhhhH.",
      "....hhhhhhHhhhhhhhH.",
      "....hhhhhhhHhhhhhH..",
      "....hhhhhhhHhhhhhH..",
      "....HhhhhhhhHhhhhH..",
      ".....HHHHHHHHHHHH...",
      "....................",
    ],
  },
] as const satisfies readonly { name: string; front: Grid; back: Grid }[];

// Headphones sit over the hair on every character.
export const HEADPHONES: Record<View, Grid> = {
  front: [
    "....................",
    "....................",
    "......==gggg........",
    "....=g8888888g......",
    "...=88.......88g....",
    "..=8...........88...",
    "..g8.............8..",
    "..g8.............8..",
    "..g8................",
    "..g8................",
    ".=ggg...............",
    "=gggg8..............",
    "=gg=g8..............",
    "=gg=g8..............",
    "gggg88..............",
    ".8888...............",
  ],
  back: [
    "....................",
    "....................",
    "........ggg==.......",
    "......g8888888g=....",
    "....g88.......88=...",
    "...88...........8=..",
    "..8..............8g.",
    "..8..............8g.",
    "..8..............8g.",
    "..8..............8g.",
    ".88.............ggg=",
    ".8.............8gg=g",
    ".8.............8gg=g",
    ".8.............8gg=g",
    "...............88ggg",
    "................888.",
  ],
};

// Flattened isometric ground shadow, centered under the foot origin at SHADOW_AT.
export const SHADOW: Grid = [
  ".....______________.....",
  "..____________________..",
  ".______________________.",
  "..____________________..",
  ".....______________.....",
];
export const SHADOW_AT = [4, 42] as const;

// One iso desk set: wood top with bevel, drawers, monitor, keyboard, mug, plant. 62x61 cells.
export const DESK: Grid = [
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..................8...........................................",
  "..................888.........................................",
  "..................8c888.......................................",
  "..................8c!!888.....................................",
  "..................8ccc!c888...................................",
  "..................8cccc!!!888.................................",
  "..................8ccc!ccc!c888...............................",
  "..................8cccc!!!cccc888.............................",
  "..................8ccc!ccc!ccccc888...........................",
  "..................8C!!c!!!c!!!cccc888.........................",
  "..................8CCC!ccc!ccc!ccccc888.......................",
  "..................8CCCC!!!ccccc!!ccccc8x......................",
  "..................888C!CCC!ccccccccccc8x......................",
  ".................:::888!!!C!!!cccccccc8x......................",
  "................:wwwww88CC!CCC!ccccccc8x......................",
  ".............:::wwwwwwww88C!!!C!!ccccc8x......................",
  "............:wwwwwwwwwwwww88CC!CCCcccc8x......................",
  ".........:::wwwwwwwwwwwwwwwwGGCCCCCCcc8x......................",
  "........:wwwwwwwwwwwwwwwwwwwGG88CCCCCC8x......e..e............",
  ".....:::wwwwwwwwwwwwwwwwwwwwGG8w8CCCCC8x.....%e.eE.e..........",
  "....:wwwwwwwwwwwwwwwwwwwWwwwGG8www8CCC8x....e%ee%Ee...........",
  "..::wwwwwwwwwwwwwwwwwwwwwWWWGG8wwwww8C8x.....eEeEEe...........",
  "..:6wwwwWwwwwwwwwwwwwwwwwwwwGg8wwwwwww8x:.....EeE9............",
  "..WW::wwwWWWwwwwwwwwwwwwwww==gggwwwwwwwww:::..gggg............",
  "..66W6:6wwwwW=gwwwwwwwwwwg=gggggggwwwwwwwwww:.=ggG............",
  "..666WWW::ww88===wwwwwwg==ggggggggggwwwwwwwww:=ggG............",
  "..666866W6g=gg8gg=gwwwwwwgggggggggwwwwwwwwwwwww88.............",
  "..6668886W88===888===wwwwwwgggggwwwwwwwwW~mmwwwww:::..........",
  "..666888886686g=gg8gg=gwwwwwwgwwwwwwwwww~777mwwwwwww:.........",
  "..666xx888886888===888===wwwwwwwwwwwwwwwmmmMmmwwwwwww:::......",
  "..666xxxx888886686g=gg8gg=gwwwwwwwWwwwwwmmmMwmWwwwwwwwww:.....",
  "..666xxxxxx888886888===888===wwwwwwWWWwwmmmMmwwwwwwwwwwww:::..",
  "..666xxxxxxxx888886686g=gg8gg=gwwwwwwwWwwMMMwwwwwwwwwwwwwwww:.",
  "..666xxxxxxxxxx888886888===88ggggwwwwwwWWWwwwwwwwwwwwwwwwwwww.",
  "....6xxxxxxxxxxxx888886686g=gggwwwwwwwwwwwWwwwwwwwwwwwwwwWwWW.",
  ".....xxxxxxxxxxxxxx888886888g:wwwwwwwwwwwwwWWwwwwwwwwwwwwWWWW.",
  ".....xxxxxxxxxxxxxxxx888886686:6wwwwwwwwwwwwwwwwwwwwwWwWWWWWW.",
  ".....xxxxxxxxxxxxxxxxxx88888WWWW::wwwwwwwwwwwwwwwwwwwWWWWWWWW.",
  ".....xxxxxxxxxxxxxxxxxxxx888W66WW6:6wwwwwwwwwwwwwWwWWWWWWW6WW.",
  ".......xxxxxxxxxxxxxxxxxxxx8W666WWWW::wwwwwwwwwwwWWWWWW666WWW.",
  ".........xxxxxxxxxxxxxxxxxxxW6666~~WW6:6wwwwwWwWWWWWWW6WWWWWW.",
  "...........xxxxxxxxxxxxxxxxxWWW6677~~WWW::wwwWWWWWW666WWWWWWW.",
  ".............xxxxxxxxxxxxxxxW66W6667766WW6wWWWWWWW6WWWWWWWWWW.",
  "...............xxxxxxxxxxxxxW666WWW66666WWWWWWW666WWWWWWWWWWW.",
  ".................xxxxxxxxxxxW6666~~W666666WWWW6WWWWWWWWWWW6WW.",
  "...................xxxxxxxxxWWW6677~~WW666WW66WWWWWWWWW666W...",
  ".....................xxxxxxxW66W6667766W66WWWWWWWWWWWW6WW.....",
  ".......................xxxxxW.66WWW66666WWWWWWWWWWW666W.......",
  ".........................xxxW...6~~W666666WWWWWWWW6WW.........",
  "...........................xW....77~~WW666WWWWW666W...........",
  "............................W......7766W66WWWW6WW.............",
  "......................................66WWWW66W...............",
  "........................................66WWW.................",
  "..........................................W...................",
];

// The same desk with the monitor off (every state but working).
export const DESK_DIM: Grid = [
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..............................................................",
  "..................8...........................................",
  "..................888.........................................",
  "..................8x888.......................................",
  "..................8x88888.....................................",
  "..................8xxx8x888...................................",
  "..................8xxxx888888.................................",
  "..................8xxx8xxx8x888...............................",
  "..................8xxxx888xxxx888.............................",
  "..................8xxx8xxx8xxxxx888...........................",
  "..................8x88x888x888xxxx888.........................",
  "..................8xxx8xxx8xxx8xxxxx888.......................",
  "..................8xxxx888xxxxx88xxxxx8x......................",
  "..................888x8xxx8xxxxxxxxxxx8x......................",
  ".................:::888888x888xxxxxxxx8x......................",
  "................:wwwww88xx8xxx8xxxxxxx8x......................",
  ".............:::wwwwwwww88x888x88xxxxx8x......................",
  "............:wwwwwwwwwwwww88xx8xxxxxxx8x......................",
  ".........:::wwwwwwwwwwwwwwwwGGxxxxxxxx8x......................",
  "........:wwwwwwwwwwwwwwwwwwwGG88xxxxxx8x......e..e............",
  ".....:::wwwwwwwwwwwwwwwwwwwwGG8w8xxxxx8x.....%e.eE.e..........",
  "....:wwwwwwwwwwwwwwwwwwwWwwwGG8www8xxx8x....e%ee%Ee...........",
  "..::wwwwwwwwwwwwwwwwwwwwwWWWGG8wwwww8x8x.....eEeEEe...........",
  "..:6wwwwWwwwwwwwwwwwwwwwwwwwGg8wwwwwww8x:.....EeE9............",
  "..WW::wwwWWWwwwwwwwwwwwwwww==gggwwwwwwwww:::..gggg............",
  "..66W6:6wwwwW=gwwwwwwwwwwg=gggggggwwwwwwwwww:.=ggG............",
  "..666WWW::ww88===wwwwwwg==ggggggggggwwwwwwwww:=ggG............",
  "..666866W6g=gg8gg=gwwwwwwgggggggggwwwwwwwwwwwww88.............",
  "..6668886W88===888===wwwwwwgggggwwwwwwwwW~mmwwwww:::..........",
  "..666888886686g=gg8gg=gwwwwwwgwwwwwwwwww~777mwwwwwww:.........",
  "..666xx888886888===888===wwwwwwwwwwwwwwwmmmMmmwwwwwww:::......",
  "..666xxxx888886686g=gg8gg=gwwwwwwwWwwwwwmmmMwmWwwwwwwwww:.....",
  "..666xxxxxx888886888===888===wwwwwwWWWwwmmmMmwwwwwwwwwwww:::..",
  "..666xxxxxxxx888886686g=gg8gg=gwwwwwwwWwwMMMwwwwwwwwwwwwwwww:.",
  "..666xxxxxxxxxx888886888===88ggggwwwwwwWWWwwwwwwwwwwwwwwwwwww.",
  "....6xxxxxxxxxxxx888886686g=gggwwwwwwwwwwwWwwwwwwwwwwwwwwWwWW.",
  ".....xxxxxxxxxxxxxx888886888g:wwwwwwwwwwwwwWWwwwwwwwwwwwwWWWW.",
  ".....xxxxxxxxxxxxxxxx888886686:6wwwwwwwwwwwwwwwwwwwwwWwWWWWWW.",
  ".....xxxxxxxxxxxxxxxxxx88888WWWW::wwwwwwwwwwwwwwwwwwwWWWWWWWW.",
  ".....xxxxxxxxxxxxxxxxxxxx888W66WW6:6wwwwwwwwwwwwwWwWWWWWWW6WW.",
  ".......xxxxxxxxxxxxxxxxxxxx8W666WWWW::wwwwwwwwwwwWWWWWW666WWW.",
  ".........xxxxxxxxxxxxxxxxxxxW6666~~WW6:6wwwwwWwWWWWWWW6WWWWWW.",
  "...........xxxxxxxxxxxxxxxxxWWW6677~~WWW::wwwWWWWWW666WWWWWWW.",
  ".............xxxxxxxxxxxxxxxW66W6667766WW6wWWWWWWW6WWWWWWWWWW.",
  "...............xxxxxxxxxxxxxW666WWW66666WWWWWWW666WWWWWWWWWWW.",
  ".................xxxxxxxxxxxW6666~~W666666WWWW6WWWWWWWWWWW6WW.",
  "...................xxxxxxxxxWWW6677~~WW666WW66WWWWWWWWW666W...",
  ".....................xxxxxxxW66W6667766W66WWWWWWWWWWWW6WW.....",
  ".......................xxxxxW.66WWW66666WWWWWWWWWWW666W.......",
  ".........................xxxW...6~~W666666WWWWWWWW6WW.........",
  "...........................xW....77~~WW666WWWWW666W...........",
  "............................W......7766W66WWWW6WW.............",
  "......................................66WWWW66W...............",
  "........................................66WWW.................",
  "..........................................W...................",
];

// Where the seated frame's top-left cell goes, relative to the desk: hands on the keyboard.
export const SEAT_OFFSET = [-8, 15] as const;

// Coffee break placement (ArtSheet): the mug sits at this frame column, the soles on this row.
export const MUG_COL = 34;
export const SOLE_ROW = 44;
